name = input("Name = ")
address = input("Address = ")
phone = input("Phone Number = +91 ")
email = input("Email Address = ")
degree_college = input("Enter your college name = ")
degree_course = input("Enter your course name = ")
university = input("Enter your university name = ")
cgpa = input("Enter your CGPA = ")
hsc_name = input("Enter your college name(hsc) = ")
hsc_percentage, hsc_group = input(
    "Enter your percentage(hsc) and group = ").split()
ssc_name = input("Enter your school name = ")
ssc_percentage = input("Enter your percentage(ssc) = ")
summary = input("Enter your summary about yourself = ")
skills = input("Enter your skills = ")
hobbies = input("Enter your hobbies = ")
print()
print(" Resume ".center(100, "|"))
print()
print("Name = ", name)
print("".center(100, "-"))
print("+91",phone, end="          ")
print(email, end="          ")
print(address)
print()
print("Summary".center(100, "-"))
print(summary)
print()
print(" Education ".center(100, "-"))
print("Graduation:")
print("College: ", degree_college)
print("University: ", university)
print("course: ", degree_course, end="     ")
print("overall cgpa: ", cgpa)
print()
print("Higher Secondary:")
print("College: ", hsc_name)
print("Percentage: ", hsc_percentage, end="     ")
print("Group: ", hsc_group)
print()
print("Secondary:")
print("School: ", ssc_name)
print("Percentage: ", ssc_percentage)
print()
print("Key Skills:".center(100, "-"))
print(skills)
print()
print("Hobbies:".center(100, "-"))
print(hobbies)
print()
print("".center(100, "|"))
