# Generated by Django 5.2 on 2025-04-16 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 15, 54, 27, 747324)),
        ),
    ]
