# Generated by Django 5.2 on 2025-04-18 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userprofile_delete_user_alter_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 4, 18, 11, 10, 36, 227265)),
        ),
    ]
